### ISSUE TITLE
not really an issue but a question 

### ISSUE THREAD

**Issue by goblinrieur** [mobluse/semigraphics#1]
hello.

I saw your video, and as a gnu-forth curious guy, I read your code, quickly for now.
I ran the game on Debian trixie with both gforth 0.7.3 & 0.7.9  successfully too

why not  use either an 
`: ESC[ 27 91 emit emit ;  `   word to be more 0.6.x to 0.7.9 (_0.7.9 will deprecate ESC[ internal_) 
or
`.\" \e[1m"` standard gforth escaped strings|escape sequences syntax 

Is this due to a windows and ANS colored compatible terminals ? or another reason ?

regards

**Comment by mobluse** [comment]
I have not tried gforth 0.7.9 and did not know `ESC[` will be deprecated, but I added `ESC[` so that this will run with later versions of GForth.
`: ESC[  27 emit [char] [ emit ; \ From /usr/share/gforth/0.7.3/vt100.fs`
